spring:
  application:
    name: eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 9000

#开启熔断器
feign:
  hystrix:
    enabled: true
#暴露endpoints
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream